version: '3'
services:
    sp_traefik:
        image: traefik:latest
        command: --web --docker --docker.domain=traefik --docker.swarmmode=true --logLevel=DEBUG --entryPoints='Name:http Address::80' --defaultentrypoints=http
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml

    sp_client:
        image: sp_client
        # volumes:
        #     - ./src/client:/usr/app
        deploy:
            labels:
                - "traefik.frontend.rule=PathPrefixStrip: /"
                - "traefik.port=3000"
                - "traefik.docker.network=superior_prospects_default"

    sp_server:
        image: sp_server
        command: npm start
        deploy:
            labels:
                - "traefik.frontend.rule=PathPrefixStrip: /api"
                - "traefik.port=4000"
                - "traefik.docker.network=superior_prospects_default"

    sp_mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        command: mongod --smallfiles

    # sp_mongo_seed:
    #     image: sp_mongo_seed
    #     deploy:
    #         restart_policy:
    #             condition: none