version: '3.1'
services:
    sp_traefik:
        image: traefik:latest
        command: --web --docker --docker.domain=traefik --docker.swarmmode=true --logLevel=DEBUG --entryPoints='Name:http Address::80' --defaultentrypoints=http
        ports:
            - "8888:80"
            - "9999:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml

    sp_client:
        image: shaunfowler/sp_client:latest
        deploy:
            labels:
                - "traefik.frontend.rule=PathPrefixStrip: /"
                - "traefik.port=3000"
                - "traefik.docker.network=superior_prospects_default"

    sp_server:
        image: shaunfowler/sp_server:latest
        secrets:
            - sp_client_id
            - sp_client_secret
        environment:
            - API_BASE_URL=http://localhost:8888/api
        deploy:
            labels:
                - "traefik.frontend.rule=PathPrefixStrip: /api"
                - "traefik.port=4000"
                - "traefik.docker.network=superior_prospects_default"

    sp_mongo:
        image: mongo:latest
        command: mongod --smallfiles

secrets:
    sp_client_id:
        external: true
    sp_client_secret:
        external: true
