version: '3'
services:
    sp_traefik:
        image: traefik:latest
        command: --web --docker --docker.domain=traefik --docker.swarmmode=true --logLevel=DEBUG --entryPoints='Name:http Address::80' --defaultentrypoints=http
        ports:
            - "8888:80"
            - "9999:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml

    sp_client:
        image: shaunfowler/sp_client:latest
        deploy:
            labels:
                - "traefik.frontend.rule=PathPrefixStrip: /"
                - "traefik.port=3000"
                - "traefik.docker.network=superior_prospects_default"

    sp_server:
        image: shaunfowler/sp_server:latest
        deploy:
            labels:
                - "traefik.frontend.rule=PathPrefixStrip: /api"
                - "traefik.port=4000"
                - "traefik.docker.network=superior_prospects_default"

    sp_mongo:
        image: mongo:latest
        command: mongod --smallfiles

    sp_mongo_seed:
        image: shaunfowler/sp_mongo_seed:latest
        deploy:
            restart_policy:
                condition: none
