{
 "title": "Superior Prospects API",
 "time": { "from": "2018-05-05T09:05:36.360Z", "to": "2018-05-05T16:30:56.136Z" },
 "panels": [
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) by (path) / sum(rate(http_request_duration_seconds_count[5m])) by (path) "
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status_code=~'^[123].*'}[5m])) by (job) /sum(rate(http_request_duration_seconds_count[5m])) by (job)"
    }
   ]
  },
  {
   "title": "99th Percentile Latency (10ms)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{le='0.01'}[5m])) / sum(rate(http_request_duration_seconds_count[5m]))"
    }
   ]
  }
 ]
}